### ISSUE TITLE
MAPK1 is a ligand

### ISSUE THREAD

**Issue by deeenes** [SCA-IRCM/LRdb#1]
Dear LRdb Team,

In line 2065 of the database file `LRdb_122019.txt`,  `MAPK1` is annotated as ligand. Afaik this protein is not a secreted ligand but an intracellular kinase. I am wondering if this annotation is a mistake or in agreement with your intentions? If it's a wrong annotation, might also other proteins be misannotated?

Best wishes,

Denes

**Comment by SCA-IRCM** [comment]
Dear Denes,
As you can see it in the figure 1. A. and in the materials & methods section of the paper (https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkaa183/5810485) several interactions were infered as "ligand/receptor ones" from reactome following a certain method. You can see here (https://www.genecards.org/cgi-bin/carddisp.pl?gene=MAPK1#localization) that MAPK1 is found in the extracellular compartment with a high confidence. Therefore this annotation is in agreement with our intentions. However we are open to discussion and thank you for your remark.
Best wishes,

Simon

**Comment by deeenes** [comment]
Hi Simon,

Thanks for your reply.

I found this annotation might come from 2 evidences:

https://www.reactome.org/content/detail/R-HSA-6798751
As it says MAPK1 present in azurophil vesicles which eventually exocytise.

And Phobius predicts MAPK1 being secreted because it has a polyalanine signal peptide 2-9 at the N terminus.

For sure I understand computational inference and data integration always comes with false positives. Here I think is important to note, the GO terms you mention in the paper include the proteins in exosomes and microvesicles which cover a major part of the human proteome, most of them have no function outside the cell (and until stay inside a vesicle practically does not present extracellular). 

Best,

Denes
